### ISSUE TITLE
最新Chromeで拡張機能がContent Security Policy違反になる。

### ISSUE THREAD

**Issue by CircleD5** [xmitoux/nai-utils#23]
最新ChromeでContent Security Policyに拡張機能がはじかれてしまうようになりました。

エラー内容はこちら。
> Refused to load the script 'chrome-extension://4c342ff5-0145-451b-9ee0-2ed921b56c3e/assets/content.ts-X3kK8Vgw.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

スタックトレースの結果、エラーで引っかかっているのはcontent.ts-loader-1yELnvrT.jsのこちらの行でした。
`      chrome.runtime.getURL("assets/content.ts-X3kK8Vgw.js")`

**提案**
ChatGPTと相談したところ、manifest.jsonファイルを変更することで解決することができました。

以下の部分で、content_security_policyにselfからのアクセスを許可し、
```
"content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'"
  }
```
あと追加で、動的URLもTrueになっていた部分をFalseにしました。
（この変更が重要かどうかは検証できていないが、一旦これも修正したほうが良いと言われたので修正しました。）
    `"use_dynamic_url": false`

この2つの変更により一旦、エラーは解消しました。
しかし、実は私自身、あまりNAI-Utilの機能を使っておらず、もしかしたら、上記の修正によって他に干渉して動かなくなる機能があるかもしれないので、恐縮ですが、確認していただけると助かります。

**Comment by xmitoux** [comment]
@CircleD5 
ご報告ありがとうございます！ ご指摘いただいた問題を修正したバージョンをリリースしました。

むしろ、補足いただいた `use_dynamic_url: true` こそがエラーの元凶だったようです。
私自身の調査だけではこの設定の問題にたどり着けなかったかもしれないので
とても助かりました！ ありがとうございました！
